server:
  port: 8085
spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost:3306/identity_db?createDatabaseIfNotExist=true
    username: root
    password: Mayank.00
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
app:
  jwt:
    secret: VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUV2l0aEF0TGVhc3QzMkNoYXJzIQ==
    expiration-ms: 3600000
admin:
  bootstrap:
    enabled: true
    username: admin
    password: admin123
    force: true
users:
  bootstrap:
    enabled: false
    force: false
    doctor:
      username: doctor
      password: doctor123
      role: ROLE_DOCTOR
    patient:
      username: patient
      password: patient123
      role: ROLE_PATIENT
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
